/*let ID = 0;
const genID = () => ((ID++).toString());*/

/*
export const SUPPLIER_LOAD = genID();
export const SUPPLIER_LOAD_SUCCESS = genID();
export const SUPPLIER_LOAD_ERROR = genID();
export const SUPPLIER_QUERY = genID();
export const SUPPLIER_EDIT = genID();
export const SUPPLIER_DELETE = genID();
export const SUPPLIER_MODAL_SHOW = genID();
export const SUPPLIER_MODAL_HIDE= genID();
export const SUPPLIER_MODAL_EDIT= genID();
export const SUPPLIER_UPDATE= genID();*/
export const SUPPLIER_LOAD = "SUPPLIER_LOAD";
export const SUPPLIER_LOAD_SUCCESS = "SUPPLIER_LOAD_SUCCESS";
export const SUPPLIER_LOAD_ERROR = "SUPPLIER_LOAD_ERROR";
export const SUPPLIER_QUERY = "SUPPLIER_QUERY";
export const SUPPLIER_EDIT = "SUPPLIER_EDIT";
export const SUPPLIER_DELETE = "SUPPLIER_DELETE";
export const SUPPLIER_UPDATE = "SUPPLIER_UPDATE";
export const SUPPLIER_ADD = "SUPPLIER_ADD";
export const SUPPLIER_MODAL_HIDE = "SUPPLIER_MODAL_HIDE";
export const SUPPLIER_MODAL_EDIT = "SUPPLIER_MODAL_EDIT";
export const SUPPLIER_MODAL_ADD = "SUPPLIER_MODAL_ADD";
export const SUPPLIER_QUICK_EDIT = "SUPPLIER_QUICK_EDIT";
export const SUPPLIER_QUICK_EDIT_SUBMIT = "SUPPLIER_QUICK_EDIT_SUBMIT";
export const SUPPLIER_QUICK_EDIT_CANCEL = "SUPPLIER_QUICK_EDIT_CANCEL";